export type RequestStatus = "open" | "pending" | "fulfilled" | "completed"

export const requestData = [
  {
    id: 1,
    title: "Need Beta AR Jacket for Weekend Hike",
    category: "Jackets",
    description:
      "I'm planning a hike in Garibaldi Provincial Park this weekend and need a waterproof shell. Looking for a men's medium Beta AR or similar.",
    timeframe: "May 15-17, 2023",
    location: "Vancouver, BC",
    credits: 2,
    status: "open" as RequestStatus,
    requester: {
      id: 1,
      name: "Sarah Johnson",
      rating: 4.8,
      memberSince: "March 2022",
      responseRate: "95%",
    },
    fulfiller: null,
    createdAt: "May 5, 2023",
    reviews: [],
  },
  {
    id: 2,
    title: "Bora AR 50 Backpack Needed for Backpacking Trip",
    category: "Backpacks",
    description:
      "Planning a 3-day backpacking trip and need a comfortable pack. Preferably the Bora AR 50 or something similar with good support for heavy loads.",
    timeframe: "June 10-15, 2023",
    location: "Vancouver, BC",
    credits: 2,
    status: "open" as RequestStatus,
    requester: {
      id: 2,
      name: "Michael Chen",
      rating: 4.9,
      memberSince: "January 2022",
      responseRate: "98%",
    },
    fulfiller: null,
    createdAt: "May 8, 2023",
    reviews: [],
  },
  {
    id: 3,
    title: "Climbing Shoes for Indoor Session",
    category: "Climbing",
    description:
      "Looking to try climbing at the local gym and need a pair of climbing shoes. I'm a US men's size 9. Any Arc'teryx climbing shoes would be great.",
    timeframe: "May 20, 2023",
    location: "North Vancouver, BC",
    credits: 1,
    status: "pending" as RequestStatus,
    requester: {
      id: 3,
      name: "James Wilson",
      rating: 4.7,
      memberSince: "February 2022",
      responseRate: "90%",
    },
    fulfiller: {
      id: 4,
      name: "Emma Wilson",
      rating: 4.8,
      memberSince: "December 2021",
      responseRate: "95%",
    },
    createdAt: "May 10, 2023",
    reviews: [],
  },
  {
    id: 4,
    title: "Alpha SV Jacket for Alpine Climb",
    category: "Jackets",
    description:
      "Planning an alpine climb in the Coast Mountains and need a durable hardshell. Looking for an Alpha SV in men's large or similar.",
    timeframe: "June 5-8, 2023",
    location: "Squamish, BC",
    credits: 3,
    status: "open" as RequestStatus,
    requester: {
      id: 5,
      name: "David Thompson",
      rating: 4.6,
      memberSince: "April 2022",
      responseRate: "85%",
    },
    fulfiller: null,
    createdAt: "May 12, 2023",
    reviews: [],
  },
  {
    id: 5,
    title: "Aerios 15 Backpack for Day Hike",
    category: "Backpacks",
    description:
      "Need a lightweight daypack for a hike in Lynn Canyon. The Aerios 15 would be perfect, but open to similar options.",
    timeframe: "May 25, 2023",
    location: "Vancouver, BC",
    credits: 1,
    status: "fulfilled" as RequestStatus,
    requester: {
      id: 6,
      name: "Olivia Martinez",
      rating: 4.9,
      memberSince: "March 2022",
      responseRate: "97%",
    },
    fulfiller: {
      id: 1,
      name: "John Doe",
      rating: 4.9,
      memberSince: "January 2022",
      responseRate: "99%",
    },
    createdAt: "May 15, 2023",
    reviews: [
      {
        id: 1,
        reviewer: {
          id: 6,
          name: "Olivia Martinez",
        },
        rating: 5,
        comment:
          "John was amazing! The backpack was in perfect condition and he was very flexible with pickup and return times.",
        date: "May 26, 2023",
      },
      {
        id: 2,
        reviewer: {
          id: 1,
          name: "John Doe",
        },
        rating: 5,
        comment: "Olivia took great care of my backpack and returned it on time. Would definitely lend to her again!",
        date: "May 26, 2023",
      },
    ],
  },
  {
    id: 6,
    title: "Atom LT Hoody for Spring Hiking",
    category: "Jackets",
    description:
      "Looking for an insulated mid-layer for spring hiking. Preferably the Atom LT in women's small, but open to similar options.",
    timeframe: "May 18-20, 2023",
    location: "Burnaby, BC",
    credits: 2,
    status: "completed" as RequestStatus,
    requester: {
      id: 7,
      name: "Sophia Kim",
      rating: 4.8,
      memberSince: "February 2022",
      responseRate: "93%",
    },
    fulfiller: {
      id: 8,
      name: "Ryan Patel",
      rating: 4.7,
      memberSince: "January 2022",
      responseRate: "90%",
    },
    createdAt: "May 10, 2023",
    reviews: [
      {
        id: 3,
        reviewer: {
          id: 7,
          name: "Sophia Kim",
        },
        rating: 5,
        comment:
          "Ryan's jacket was perfect for my hike! It was in great condition and kept me warm during the chilly mornings.",
        date: "May 21, 2023",
      },
      {
        id: 4,
        reviewer: {
          id: 8,
          name: "Ryan Patel",
        },
        rating: 5,
        comment:
          "Sophia was a pleasure to work with and returned the jacket in perfect condition. Would definitely lend to her again!",
        date: "May 21, 2023",
      },
    ],
  },
  {
    id: 7,
    title: "Acrux TR GTX Boots for Wet Conditions",
    category: "Footwear",
    description:
      "Need waterproof hiking boots for a trip to the West Coast Trail. Looking for Acrux TR GTX or similar in men's size 10.",
    timeframe: "June 15-22, 2023",
    location: "Victoria, BC",
    credits: 2,
    status: "open" as RequestStatus,
    requester: {
      id: 9,
      name: "Alex Rivera",
      rating: 4.5,
      memberSince: "April 2022",
      responseRate: "88%",
    },
    fulfiller: null,
    createdAt: "May 20, 2023",
    reviews: [],
  },
  {
    id: 8,
    title: "Granville 20 Backpack for City Trip",
    category: "Backpacks",
    description:
      "Traveling to Seattle for a weekend and need a sleek backpack for carrying essentials. The Granville 20 would be perfect.",
    timeframe: "May 27-29, 2023",
    location: "Vancouver, BC",
    credits: 1,
    status: "open" as RequestStatus,
    requester: {
      id: 10,
      name: "Jessica Lee",
      rating: 4.9,
      memberSince: "March 2022",
      responseRate: "96%",
    },
    fulfiller: null,
    createdAt: "May 22, 2023",
    reviews: [],
  },
]

export const categories = [
  { id: 1, name: "Jackets", icon: "jacket" },
  { id: 2, name: "Backpacks", icon: "backpack" },
  { id: 3, name: "Climbing", icon: "climbing" },
  { id: 4, name: "Footwear", icon: "footwear" },
  { id: 5, name: "Pants", icon: "pants" },
  { id: 6, name: "Base Layers", icon: "base-layers" },
  { id: 7, name: "Accessories", icon: "accessories" },
]

// Mock current user data
export const currentUser = {
  id: 1,
  name: "John Doe",
  credits: 3,
  memberSince: "January 2022",
  location: "Vancouver, BC",
  rating: 4.9,
  reviewCount: 12,
  requestsFulfilled: 5,
  requestsMade: 3,
}

export const gearData = [
  {
    id: 1,
    name: "Alpha SV Jacket",
    category: "Jackets",
    condition: "Excellent",
    description:
      "The Arc'teryx Alpha SV Jacket is the flagship of the Arc'teryx hardshell line, built for severe alpine conditions.",
    credits: 2,
    location: "Vancouver, BC",
    image: "/placeholder.svg?height=500&width=500",
    availability: "Available for the next 2 weeks",
    owner: {
      id: 1,
      name: "John Doe",
      rating: 4.9,
      memberSince: "January 2022",
      responseRate: "99%",
      responseTime: "Within 1 hour",
    },
    reviews: [
      {
        id: 1,
        name: "Sarah Johnson",
        rating: 5,
        comment: "Great jacket! Perfect for my hiking trip.",
        date: "May 10, 2023",
      },
      {
        id: 2,
        name: "Michael Chen",
        rating: 4,
        comment: "Good jacket, but a bit worn.",
        date: "May 12, 2023",
      },
    ],
    careInstructions: "Machine wash cold, tumble dry low",
    retailPrice: 799,
    sizing: "Men's Medium",
  },
  {
    id: 2,
    name: "Bora AR 50 Backpack",
    category: "Backpacks",
    condition: "Good",
    description: "The Arc'teryx Bora AR 50 Backpack is a durable and comfortable pack for multi-day backpacking trips.",
    credits: 1,
    location: "North Vancouver, BC",
    image: "/placeholder.svg?height=500&width=500",
    availability: "Available starting June 1st",
    owner: {
      id: 2,
      name: "Emma Wilson",
      rating: 4.8,
      memberSince: "December 2021",
      responseRate: "95%",
      responseTime: "Within 3 hours",
    },
    reviews: [
      {
        id: 3,
        name: "David Thompson",
        rating: 5,
        comment: "Excellent backpack! Very comfortable and durable.",
        date: "May 15, 2023",
      },
      {
        id: 4,
        name: "Olivia Martinez",
        rating: 3,
        comment: "The backpack was a bit dirty.",
        date: "May 18, 2023",
      },
    ],
    careInstructions: "Spot clean only",
    retailPrice: 350,
  },
  {
    id: 3,
    name: "Konseal AR Climbing Shoes",
    category: "Climbing",
    condition: "Like New",
    description: "The Arc'teryx Konseal AR Climbing Shoes are high-performance shoes for advanced climbers.",
    credits: 3,
    location: "Squamish, BC",
    image: "/placeholder.svg?height=500&width=500",
    availability: "Available immediately",
    owner: {
      id: 3,
      name: "Ryan Patel",
      rating: 4.7,
      memberSince: "January 2022",
      responseRate: "90%",
      responseTime: "Within 6 hours",
    },
    reviews: [
      {
        id: 5,
        name: "Sophia Kim",
        rating: 5,
        comment: "Amazing climbing shoes! Great grip and comfortable fit.",
        date: "May 20, 2023",
      },
      {
        id: 6,
        name: "Alex Rivera",
        rating: 5,
        comment: "Shoes were in perfect condition!",
        date: "May 22, 2023",
      },
    ],
    careInstructions: "Wipe clean with a damp cloth",
    retailPrice: 180,
    sizing: "US Men's 9",
  },
  {
    id: 4,
    name: "Atom LT Hoody",
    category: "Jackets",
    condition: "Used",
    description: "The Arc'teryx Atom LT Hoody is a versatile insulated mid-layer for various activities.",
    credits: 1,
    location: "Burnaby, BC",
    image: "/placeholder.svg?height=500&width=500",
    availability: "Available for the next month",
    owner: {
      id: 4,
      name: "Jessica Lee",
      rating: 4.9,
      memberSince: "March 2022",
      responseRate: "96%",
      responseTime: "Within 12 hours",
    },
    reviews: [],
    careInstructions: "Machine wash warm, tumble dry low",
    retailPrice: 250,
    sizing: "Women's Small",
  },
  {
    id: 5,
    name: "Acrux TR GTX Boots",
    category: "Footwear",
    condition: "Excellent",
    description: "The Arc'teryx Acrux TR GTX Boots are waterproof hiking boots for challenging terrain.",
    credits: 2,
    location: "Victoria, BC",
    image: "/placeholder.svg?height=500&width=500",
    availability: "Available starting July 1st",
    owner: {
      id: 5,
      name: "Sophia Kim",
      rating: 4.8,
      memberSince: "February 2022",
      responseRate: "93%",
      responseTime: "Within 24 hours",
    },
    reviews: [],
    careInstructions: "Clean with a boot brush and waterproof spray",
    retailPrice: 320,
    sizing: "US Men's 10",
  },
  {
    id: 6,
    name: "Granville 20 Backpack",
    category: "Backpacks",
    condition: "Good",
    description: "The Arc'teryx Granville 20 Backpack is a sleek and minimalist pack for urban commutes.",
    credits: 1,
    location: "Vancouver, BC",
    image: "/placeholder.svg?height=500&width=500",
    availability: "Available immediately",
    owner: {
      id: 6,
      name: "David Thompson",
      rating: 4.6,
      memberSince: "April 2022",
      responseRate: "85%",
      responseTime: "Within 2 days",
    },
    reviews: [],
    careInstructions: "Spot clean only",
    retailPrice: 160,
  },
]

