export const gearData = [
    {
      id: 1,
      name: "Beta AR Jacket",
      category: "Jackets",
      description:
        "A versatile, all-round waterproof jacket for alpine climbing and backcountry touring. Made with GORE-TEX Pro fabric for enhanced durability and breathability.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Excellent",
      location: "Vancouver, BC",
      credits: 2,
      availability: "Available most weekends",
      sizing: "Men's Medium",
      retailPrice: 600,
      careInstructions: "Machine wash cold, gentle cycle. Tumble dry low. Do not iron or dry clean.",
      owner: {
        name: "Michael Chen",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.9,
        memberSince: "March 2022",
        responseRate: "98%",
        responseTime: "Within 2 hours",
      },
      reviews: [
        {
          name: "Sarah Johnson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "April 15, 2023",
          comment:
            "Jacket was in perfect condition and Michael was very responsive. Would definitely borrow from him again!",
        },
        {
          name: "David Thompson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "March 22, 2023",
          comment: "Great experience! The jacket kept me completely dry during a rainy hike. Highly recommend.",
        },
        {
          name: "Emma Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "February 10, 2023",
          comment: "Jacket was as described and worked well for my ski trip. Michael was easy to coordinate with.",
        },
      ],
    },
    {
      id: 2,
      name: "Alpha SV Jacket",
      category: "Jackets",
      description:
        "The most durable waterproof shell in the Arc'teryx lineup, designed for severe alpine conditions. Made with N100p-X 3L GORE-TEX Pro fabric for maximum protection.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Like New",
      location: "Vancouver, BC",
      credits: 3,
      availability: "Available weekdays and most weekends",
      sizing: "Men's Large",
      retailPrice: 800,
      careInstructions: "Machine wash cold, gentle cycle. Tumble dry low. Do not iron or dry clean.",
      owner: {
        name: "Ryan Patel",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.8,
        memberSince: "January 2022",
        responseRate: "95%",
        responseTime: "Within 3 hours",
      },
      reviews: [
        {
          name: "James Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 5, 2023",
          comment: "This jacket is bombproof! Kept me completely dry during a heavy storm. Ryan was great to work with.",
        },
        {
          name: "Olivia Martinez",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "April 12, 2023",
          comment: "Excellent jacket and easy pickup/dropoff process. Would borrow again.",
        },
      ],
    },
    {
      id: 3,
      name: "Bora AR 50 Backpack",
      category: "Backpacks",
      description:
        "A comfortable and supportive backpack designed for multi-day trips. Features the RotoGlide™ hip belt that moves with your body for enhanced comfort and stability.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Good",
      location: "North Vancouver, BC",
      credits: 2,
      availability: "Available most weekends",
      sizing: "Regular",
      retailPrice: 500,
      careInstructions: "Hand wash with mild soap. Air dry away from direct heat or sunlight.",
      owner: {
        name: "Emma Wilson",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.7,
        memberSince: "February 2022",
        responseRate: "90%",
        responseTime: "Within 5 hours",
      },
      reviews: [
        {
          name: "Michael Chen",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 20, 2023",
          comment: "Great backpack for my weekend trip. Very comfortable and plenty of storage. Emma was very helpful.",
        },
        {
          name: "Sarah Johnson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "April 30, 2023",
          comment: "Backpack was in good condition and worked well for my hiking trip. Easy pickup and return process.",
        },
      ],
    },
    {
      id: 4,
      name: "Aerios 15 Backpack",
      category: "Backpacks",
      description:
        "A lightweight and versatile daypack designed for fast-paced activities. Features multiple pockets for organization and a hydration bladder compartment.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Excellent",
      location: "Vancouver, BC",
      credits: 1,
      availability: "Available weekdays and weekends",
      sizing: "One Size",
      retailPrice: 130,
      careInstructions: "Hand wash with mild soap. Air dry away from direct heat or sunlight.",
      owner: {
        name: "John Doe",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.9,
        memberSince: "January 2023",
        responseRate: "99%",
        responseTime: "Within 1 hour",
      },
      reviews: [
        {
          name: "James Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 25, 2023",
          comment:
            "Perfect daypack for my trail run. Lightweight and comfortable. John was very responsive and flexible with pickup/return times.",
        },
        {
          name: "Sophia Kim",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 10, 2023",
          comment: "Great backpack and great experience borrowing from John. Would definitely recommend!",
        },
      ],
    },
    {
      id: 5,
      name: "Konseal AR Climbing Shoes",
      category: "Footwear",
      description:
        "Versatile climbing shoes designed for all-day comfort on multi-pitch routes. Features a moderately stiff midsole for support on edges and a padded tongue for comfort.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Good",
      location: "Squamish, BC",
      credits: 1,
      availability: "Available weekends",
      sizing: "Men's US 10",
      retailPrice: 170,
      careInstructions: "Hand wash with mild soap. Air dry away from direct heat or sunlight.",
      owner: {
        name: "Emma Wilson",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.7,
        memberSince: "February 2022",
        responseRate: "90%",
        responseTime: "Within 5 hours",
      },
      reviews: [
        {
          name: "David Thompson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "May 15, 2023",
          comment:
            "Shoes were comfortable and performed well on granite. Emma was easy to coordinate with for pickup and return.",
        },
        {
          name: "Michael Chen",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "April 20, 2023",
          comment: "Great climbing shoes for all-day routes. Would definitely borrow again.",
        },
      ],
    },
    {
      id: 6,
      name: "Granville 20 Backpack",
      category: "Backpacks",
      description:
        "A sleek and durable urban backpack with a clean aesthetic. Features a padded laptop sleeve, multiple organization pockets, and weather-resistant construction.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Like New",
      location: "Vancouver, BC",
      credits: 1,
      availability: "Available weekdays and weekends",
      sizing: "One Size",
      retailPrice: 170,
      careInstructions: "Spot clean with mild soap and water. Air dry away from direct heat or sunlight.",
      owner: {
        name: "John Doe",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.9,
        memberSince: "January 2023",
        responseRate: "99%",
        responseTime: "Within 1 hour",
      },
      reviews: [
        {
          name: "Sarah Johnson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 30, 2023",
          comment:
            "Perfect backpack for my weekend trip to the city. Plenty of organization and looks great. John was very responsive and helpful.",
        },
        {
          name: "Olivia Martinez",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 15, 2023",
          comment: "Excellent backpack and excellent experience borrowing from John. Would definitely recommend!",
        },
      ],
    },
    {
      id: 7,
      name: "Atom LT Hoody",
      category: "Jackets",
      description:
        "A versatile, lightweight insulated jacket that works as a mid-layer or standalone piece. Features Coreloft™ synthetic insulation for warmth even when wet.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Excellent",
      location: "Burnaby, BC",
      credits: 2,
      availability: "Available most weekends",
      sizing: "Women's Medium",
      retailPrice: 300,
      careInstructions: "Machine wash cold, gentle cycle. Tumble dry low. Do not iron or dry clean.",
      owner: {
        name: "Sophia Kim",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.8,
        memberSince: "March 2022",
        responseRate: "95%",
        responseTime: "Within 4 hours",
      },
      reviews: [
        {
          name: "Emma Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 10, 2023",
          comment:
            "Perfect jacket for my spring hiking trip. Lightweight but warm. Sophia was very responsive and flexible with pickup/return times.",
        },
        {
          name: "Sarah Johnson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "April 25, 2023",
          comment: "Great jacket and easy borrowing experience. Would definitely borrow from Sophia again.",
        },
      ],
    },
    {
      id: 8,
      name: "Acrux TR GTX Boots",
      category: "Footwear",
      description:
        "Durable and supportive hiking boots designed for technical terrain. Features GORE-TEX waterproofing and a Vibram® Megagrip outsole for excellent traction.",
      image: "/placeholder.svg?height=400&width=600",
      condition: "Good",
      location: "Vancouver, BC",
      credits: 2,
      availability: "Available weekends",
      sizing: "Men's US 9",
      retailPrice: 250,
      careInstructions: "Clean with a damp cloth and mild soap. Air dry away from direct heat or sunlight.",
      owner: {
        name: "Ryan Patel",
        avatar: "/placeholder.svg?height=40&width=40",
        rating: 4.8,
        memberSince: "January 2022",
        responseRate: "95%",
        responseTime: "Within 3 hours",
      },
      reviews: [
        {
          name: "David Thompson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 20, 2023",
          comment:
            "These boots were perfect for my backpacking trip. Great support and traction on wet rocks. Ryan was very helpful with sizing advice.",
        },
        {
          name: "James Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "April 15, 2023",
          comment: "Comfortable boots with excellent ankle support. Would borrow again for future hikes.",
        },
      ],
    },
  ]
  
  export const hikeData = [
    {
      id: 1,
      name: "Garibaldi Lake Trail",
      location: "Whistler, BC",
      rating: 4.7,
      reviews: [
        {
          name: "Sarah Johnson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 10, 2023",
          comment:
            "Amazing hike with stunning views of Garibaldi Lake. The trail is well-maintained and the scenery is breathtaking. Highly recommended!",
        },
        {
          name: "Michael Chen",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "May 15, 2023",
          comment:
            "Beautiful lake and surrounding mountains. The hike is a bit challenging but definitely worth it. Be sure to bring plenty of water and snacks.",
        },
        {
          name: "Jessica Lee",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 20, 2023",
          comment:
            "One of the best hikes I've ever done! The turquoise water of Garibaldi Lake is simply magical. The trail is a bit crowded on weekends, so try to go during the week if possible.",
        },
        {
          name: "David Thompson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "May 25, 2023",
          comment:
            "Great hike with rewarding views. The trail is a bit rocky in some sections, so wear sturdy hiking shoes. The lake is a perfect spot for a picnic lunch.",
        },
        {
          name: "Emma Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "May 30, 2023",
          comment:
            "Absolutely stunning hike! The views of Garibaldi Lake are unforgettable. The trail is well-marked and easy to follow. A must-do for any hiker in the Whistler area.",
        },
      ],
      tips: [
        {
          name: "Sarah Johnson",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "May 10, 2023",
          content: "Bring plenty of water and snacks, as the hike is quite long and strenuous.",
          likes: 15,
        },
        {
          name: "Michael Chen",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "May 15, 2023",
          content: "Wear sturdy hiking shoes, as the trail is rocky in some sections.",
          likes: 12,
        },
        {
          name: "Jessica Lee",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "May 20, 2023",
          content: "Try to go during the week to avoid the crowds.",
          likes: 10,
        },
        {
          name: "David Thompson",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "May 25, 2023",
          content: "The lake is a perfect spot for a picnic lunch.",
          likes: 8,
        },
        {
          name: "Emma Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "May 30, 2023",
          content: "Check the weather forecast before you go, as the conditions can change quickly in the mountains.",
          likes: 6,
        },
      ],
      recommendedGear: [
        {
          name: "Arc'teryx Beta AR Jacket",
          category: "Jackets",
          price: 600,
          image: "/placeholder.svg?height=64&width=64",
        },
        {
          name: "Arc'teryx Bora AR 50 Backpack",
          category: "Backpacks",
          price: 500,
          image: "/placeholder.svg?height=64&width=64",
        },
        {
          name: "Arc'teryx Konseal AR Shoes",
          category: "Footwear",
          price: 170,
          image: "/placeholder.svg?height=64&width=64",
        },
      ],
      image: "/placeholder.svg?height=800&width=1200",
      duration: "5-6 hours",
      distance: 9,
      difficulty: "Moderate",
      bestTime: "July-September",
      facilities: "Washrooms at trailhead",
      safetyTips: "Check weather conditions, bring bear spray",
    },
    {
      id: 2,
      name: "Joffre Lakes Trail",
      location: "Pemberton, BC",
      rating: 4.8,
      reviews: [
        {
          name: "Olivia Martinez",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "June 5, 2023",
          comment:
            "Three stunning turquoise lakes! The hike is relatively easy and the views are incredible. A must-see in the Pemberton area.",
        },
        {
          name: "James Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 4,
          date: "June 10, 2023",
          comment:
            "Beautiful lakes and surrounding mountains. The trail is a bit crowded, especially on weekends. Be sure to arrive early to avoid the crowds.",
        },
        {
          name: "Sophia Kim",
          avatar: "/placeholder.svg?height=40&width=40",
          rating: 5,
          date: "June 15, 2023",
          comment:
            "One of the most beautiful hikes I've ever done! The turquoise water of the lakes is simply breathtaking. The trail is well-maintained and easy to follow.",
        },
      ],
      tips: [
        {
          name: "Olivia Martinez",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "June 5, 2023",
          content: "Arrive early to avoid the crowds, especially on weekends.",
          likes: 18,
        },
        {
          name: "James Wilson",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "June 10, 2023",
          content: "Bring a camera to capture the stunning views of the lakes.",
          likes: 15,
        },
        {
          name: "Sophia Kim",
          avatar: "/placeholder.svg?height=40&width=40",
          date: "June 15, 2023",
          content: "Wear comfortable shoes, as the trail is a bit rocky in some sections.",
          likes: 12,
        },
      ],
      recommendedGear: [
        {
          name: "Arc'teryx Atom LT Hoody",
          category: "Jackets",
          price: 300,
          image: "/placeholder.svg?height=64&width=64",
        },
        {
          name: "Arc'teryx Aerios 15 Backpack",
          category: "Backpacks",
          price: 130,
          image: "/placeholder.svg?height=64&width=64",
        },
        {
          name: "Arc'teryx Acrux TR GTX Boots",
          category: "Footwear",
          price: 250,
          image: "/placeholder.svg?height=64&width=64",
        },
      ],
      image: "/placeholder.svg?height=800&width=1200",
      duration: "3-4 hours",
      distance: 5,
      difficulty: "Easy",
      bestTime: "June-October",
      facilities: "Washrooms at trailhead",
      safetyTips: "Stay on marked trails, be aware of wildlife",
    },
  ]
  
  